### PR TITLE
Trim strings in terms of Unicode width instead of bytes

### LINKED ISSUE #96: Line width should be computed in terms of Unicode width
The code I wrote to limit the length of lines is currently counting bytes and making sure not to split any codepoints in half, but when there are many Unicode characters it won't correctly determine the width.

### PR DESCRIPTION
**Pull request by porglezomp**
Fixes #96

### CODE REVIEW

**Comment by porglezomp** [comment]
Hm, rustfmt is failing because it measures line lengths in bytes instead of unicode width, which is ironic here. Let me reformat this and retry.

**Comment by vitiral** [comment]
It looks like rustfmt really doesn't like something... I have no idea what could be going wrong here. Is it possible you have a very old version of rustfmt or have configured yours differently?

**Comment by vitiral** [comment]
It looks like the issue is that travis is using a new version of rustfmt. I think we'll just look at the app veyor info until I get back

**Comment by porglezomp** [comment]
It looks like rustfmt just got a minor version update 2 days ago. Presumably the last time I updated my rustfmt was only hours before the new version. Oops!

**Comment by vitiral** [comment]
If you want to just run rustfmt and submit a PR I'll accept it!

**Pull request merged**
