### PR TITLE
documentation overhaul

### LINKED ISSUE #69: docs are hard to understand
especially it seems like the partof relationship is presented the wrong way around, the docs continiously say that parents are partof their children.

### LINKED ISSUE #73: Use git book instead of wiki
Worst thing is wiki doesn't support mobile viewing

### LINKED ISSUE #74: Make docs for multiple partof better
the way it currently is its not clear that its possible for one artifact to be partof multiple other artifacts, and the syntax is not obvious either, as you need to put a "," in between, spaces are just silently stripped.

it would be better to use an actual toml array for this.

### PR DESCRIPTION
**Pull request by vitiral**
This is to move the documentation off of the wiki and make Simple Quality book the primary user guide. After this is merged the Wiki will be ONLY for contributor guides (other guides will be removed)

Fixes:
- fix #73 
- fix #74 
- fix #69 

This moves the docs to the `docs/` folder and adds:
- `CheatSheet.md`: for those already familiar with artifact or need a reference
- `QuickGuide.md`: quick overview for those who want to see what the tool is capable of or who have experience tracking requirements.

### CODE REVIEW

**Comment by vitiral** [comment]
TODOs before merge:
- this requires updates to the Simple Quality book

**Comment by iqualfragile** [comment]
well, there should be one 1-2 pages long document getting someone that has no idea what artifact is about started on the basics, i don't see that happening in the proposed setup.

**Comment by vitiral** [comment]
That is what QuickStart.md is for. What further detail should be added?

**Comment by vitiral** [comment]
I think I know what you are asking, and I think the README is the right place to do it. I'll see what I can do.

**Comment by vitiral** [comment]
@iqualfragile I have updated the README to have more detail about the purpose of the project. Is this going in the right direction?

**Comment by vitiral** [comment]
agh, something is wrong with that link

**Comment by vitiral** [comment]
just pushed changes to the README to address your comments. Is that closer?

**Comment by iqualfragile** [comment]
yes, this is definitly better, it now explains what requirements, specifications and design documents are, and what artifact does (with them)

**Comment by vitiral** [comment]
Do the other docs look good in this context? Thanks for all the feedback!

**Comment by vitiral** [comment]
I'm going to go ahead and merge these. If there are other issues please open tickets!

**Comment by vitiral** [comment]
did this wrong, was merged in:

https://github.com/vitiral/artifact/commit/6a6d5de1128cf149ce4cb4d0a6a45fd4bb743839

**Pull request closed without merging**
